[package]
name = "pacman"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pacman"
path = "src/main.rs"


[[bin]]
name = "encrypted_server"
path = "src/encrypted_server.rs"

[[bin]]
name = "encrypted_client"
path = "src/encrypted_client.rs"

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http = "0.2.9"
rustls = "0.21"
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
clap = { version = "4.5.24", features = ["derive"] }

boa_engine = "0.20.0"
boa_parser = "0.20.0"

tls-parser = "0.12.2"
nom = "7.1.3"
bytes = "1.9.0"
base32 = "0.5.1"
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }
futures = "0.3.31"