[package]
name = "pacman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1", features = ["full"] }
hyper-tls = "0.6.0"
hyper-util = "0.1.10"
http = "0.2.9"
tower = "0.5.2"
rustls = "0.21"
tokio-rustls = "0.24"
rustls-pemfile = "1.0"