[package]
name = "encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
http-body-util = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
base32 = "0.5.1"

